#!/bin/bash -e

# Enable the TypixDeck display / touch / backlight overlays in config.txt.
#
# The base config.txt is generated by stage1/00-boot-files; this step only
# appends to the copy inside the rootfs (never edit the stage1 file from
# here). The whole block is guarded by a marker line so re-running the stage
# is idempotent.
#
# Audio: on BCM283x models (CM4/Zero/...) the on-board analog audio driver
# (snd_bcm2835, enabled by the stock "dtparam=audio=on") claims the same
# BCM283x PWM block that the pwm-backlight-3inch2-bcm overlay needs for the
# backlight, so the global "dtparam=audio=on" is commented out and audio is
# re-enabled only on Pi 5 / CM5, where audio does not live on the legacy PWM
# controller (the backlight uses the separate RP1 PWM there anyway).

CONFIG="${ROOTFS_DIR}/boot/firmware/config.txt"
MARKER="# --- TypixDeck hardware (typixdeck-stage) ---"

if ! grep -qxF "${MARKER}" "${CONFIG}"; then
	sed -i 's|^dtparam=audio=on$|#dtparam=audio=on  # TypixDeck: BCM PWM is used by the backlight; re-enabled for pi5/cm5 below|' "${CONFIG}"

	cat >> "${CONFIG}" << EOF

${MARKER}
[cm4]
otg_mode=1
[cm5]
dtoverlay=dwc2,dr_mode=host

[all]
dtoverlay=vc4-kms-dpi-3inch2-1024x768
dtoverlay=gt911-touch-3inch2-1024x768
enable_uart=0

# PWM backlight overlays MUST come after the DPI overlay (they attach to /panel)
[cm5]
dtoverlay=pwm-backlight-3inch2-rp1
[cm4]
dtoverlay=pwm-backlight-3inch2-bcm
[pi3]
dtoverlay=pwm-backlight-3inch2-bcm
[pi0]
dtoverlay=pwm-backlight-3inch2-bcm

# On-board audio is safe where it does not sit on the BCM283x PWM block
[pi5]
dtparam=audio=on
[cm5]
dtparam=audio=on
[all]
# --- end TypixDeck hardware ---
EOF
fi
